version: "3.4"
services:
  
  dotnet:
    image: linBox:5000/restdotnet:v1.2.3
    build:
      context: ./../rest-api-dotnet
    ports:
      - "8010:5002"
      - "8011:5001"
    working_dir: /src
    entrypoint: dotnet run -p ProductAPI/ProductAPI.csproj
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any

  node:
    image: linBox:5000/restnode:v3.2.1
    build:
      context: ./../rest-client-node
    ports:
      - "8012:4000"
    working_dir: /src
    entrypoint: "sh -c 'ng serve --host $${hostname} --disable-host-check'"
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: any

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8012:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
volumes:
  rest-data:
